version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    image: express/unposting-jurnal-be-dev:v1.0.0
    container_name: unposting-jurnal-be-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DB_HOST_DEVELOPMENT=host.docker.internal
      - DB_PORT_DEVELOPMENT=5432
      - DB_USER_DEVELOPMENT=postgres
      - DB_PWD_DEVELOPMENT=admin
      - DB_NAME_DEVELOPMENT=unposting_jurnal
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - /app/node_modules
